on:
  issues:
    types: [opened]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Hello, HTTP Request Action
        id: helloRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://httpbin.org/get'
          method: 'GET'
      - name: Show Response
        run: |
          echo ${{ steps.helloRequest.outputs.response }}
          echo ${{ steps.helloRequest.outputs.headers }}
          echo ${{ fromJson(steps.helloRequest.outputs.response).origin }}
